### ISSUE TITLE
breaks with betterdiscord

### ISSUE THREAD

**Issue by fuzebox1** [CircuitRCAY/Duvbox#1]
I put duvbox.css as duvbox.theme.css in the betterdiscord themes folder and BD wont load.
If i only use the css code and put it in custom css then it works fine. well lots of errors but works.
Any idea why this is?

**Comment by CircuitRCAY** [comment]
Do you have any stacktraces from BetterDiscord? It may help me understand your issue.On 4 Aug. 2020 9:40 pm, fuzebox1 <notifications@github.com> wrote:
I put duvbox.css as duvbox.theme.css in the betterdiscord themes folder and BD wont load.
If i only use the css code and put it in custom css then it works fine. well lots of errors but works.
Any idea why this is?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
Email domain proudly hosted at migadu.com

**Comment by CircuitRCAY** [comment]
A speculation that I have is that I do not have the metadata string that BetterDiscord requires. Since I do not actually use BD, I generally test on Powercord and BeautifulDiscord. I will make a commit that fixes that issue tomorrow or in the coming days.

**Comment by fuzebox1** [comment]
Idk how to do a stacktrace from bd.
I tried copying a meta data string from another theme, and now it works.
Thanks!
